[package]
name = "sopaste"
version = "0.1.0"
authors = ["Joakim Soderlund <joakim.soderlund@gmail.com>"]
edition = "2018"

[profile.release]
codegen-units = 1
lto = true

[dependencies.askama]
version = "0.10"

[dependencies.crc]
git = "https://github.com/mrhooray/crc-rs.git"

[dependencies.chrono]
version = "0.4"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket.git"
features = ["tls"]

[dependencies.rocket_sync_db_pools]
git = "https://github.com/SergioBenitez/Rocket.git"

[dependencies.sqlx]
version = "0.5"
features = ["chrono", "mysql", "runtime-tokio-rustls"]
