[package]
name = "sopaste"
version = "0.1.0"
authors = ["Joakim Soderlund <joakim.soderlund@gmail.com>"]
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
strip = true

[dependencies.askama]
version = "0.11"

[dependencies.crc]
version = "3.0"

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["clock", "std"]

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["tls"]

[dependencies.sea-orm]
version = "0.9"
features = ["runtime-tokio-rustls", "sqlx-mysql"]

[dependencies.sea-orm-rocket]
version = "0.5"

[dependencies.syntect]
version = "5.0"

[dependencies.sqlx]
version = "0.6"
features = ["chrono", "mysql", "runtime-tokio-rustls"]
