[package]
name = "sopaste"
version = "0.1.0"
authors = ["Joakim Soderlund <joakim.soderlund@gmail.com>"]
edition = "2018"

[profile.release]
codegen-units = 1
lto = true

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket.git"
