name: Main

on:
  - pull_request
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target

    - name: Build Project
      run: cargo build --verbose

    - name: Run Tests
      run: cargo test --verbose
